-- 1. Enable UUID extension (optional, but good for IDs if needed, using BIGINT for simplicity as requested)

-- 2. Create 'users' table (Smart Login)
CREATE TABLE IF NOT EXISTS users (
  nickname TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- If table already exists, run this:
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- 3. Create 'rooms' table
CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create 'messages' table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  nickname TEXT REFERENCES users(nickname),
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Turn off RLS (Row Level Security) for public access relative to this usage
--    Or create policies. For a movie prop, disabling RLS is easiest to avoid permission errors via API.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Allow public access (Anon key) for everything - easiest for this Node.js server usage
DROP POLICY IF EXISTS "Public Access Users" ON users;
CREATE POLICY "Public Access Users" ON users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Access Rooms" ON rooms;
CREATE POLICY "Public Access Rooms" ON rooms FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Access Messages" ON messages;
CREATE POLICY "Public Access Messages" ON messages FOR ALL USING (true) WITH CHECK (true);
